export default {
  selected: [
    {
      image: require("../../static/img/papers/thumb/geonetverse.png").default,
      authors:
        "Zikun Deng, Shifu Chen, Xiao Xie, Guodao Sun, Mingliang Xu, <u>Di Weng*</u>, Yingcai Wu*",
      title: "Multilevel Visual Analysis of Aggregate Geo-Networks",
      venue:
        "IEEE Transactions on Visualization and Computer Graphics (Early Access)",
      doi: "10.1109/TVCG.2022.3229953",
      abstract:
        "Numerous patterns found in urban phenomena, such as air pollution and human mobility, can be characterized as many directed geospatial networks (geo-networks) that represent spreading processes in urban space. These geo-networks can be analyzed from multiple levels, ranging from the macro-level of summarizing all geo-networks, meso-level of comparing or summarizing parts of geo-networks, and micro-level of inspecting individual geo-networks. Most of the existing visualizations cannot support multilevel analysis well. These techniques work by: 1) showing geo-networks separately with multiple maps leads to heavy context switching costs between different maps; 2) summarizing all geo-networks into a single network can lead to the loss of individual information; 3) drawing all geo-networks onto one map might suffer from the visual scalability issue in distinguishing individual geo-networks. In this study, we propose GeoNetverse, a novel visualization technique for analyzing aggregate geo-networks from multiple levels. Inspired by metro maps, GeoNetverse balances the overview and details of the geo-networks by placing the edges shared between geo-networks in a stacked manner. To enhance the visual scalability, GeoNetverse incorporates a level-of-detail rendering, a progressive crossing minimization, and a coloring technique. A set of evaluations was conducted to evaluate GeoNetverse from multiple perspectives.",
    },
    {
      image: require("../../static/img/papers/thumb/ecoalvis.png").default,
      authors:
        "Shuhan Liu, <u>Di Weng*</u>, Yuan Tian, Zikun Deng, Haoran Xu, Xiangyu Zhu, Honglei Yin, Xianyuan Zhan, Yingcai Wu",
      title:
        "ECoalVis: Visual Analysis of Control Strategies in Coal-fired Power Plants",
      venue:
        "IEEE Transactions on Visualization and Computer Graphics, vol. 29, no. 1, pp. 1091-1101, Jan. 2023",
      doi: "10.1109/TVCG.2022.3209430",
      abstract:
        "Improving the efficiency of coal-fired power plants has numerous benefits. The control strategy is one of the major factors affecting such efficiency. However, due to the complex and dynamic environment inside the power plants, it is hard to extract and evaluate control strategies and their cascading impact across massive sensors. Existing manual and data-driven approaches cannot well support the analysis of control strategies because these approaches are time-consuming and do not scale with the complexity of the power plant systems. Three challenges were identified: a) interactive extraction of control strategies from large-scale dynamic sensor data, b) intuitive visual representation of cascading impact among the sensors in a complex power plant system, and c) time-lag-aware analysis of the impact of control strategies on electricity generation efficiency. By collaborating with energy domain experts, we addressed these challenges with ECoalVis, a novel interactive system for experts to visually analyze the control strategies of coal-fired power plants extracted from historical sensor data. The effectiveness of the proposed system is evaluated with two usage scenarios on a real-world historical dataset and received positive feedback from experts.",
    },
    {
      image: require("../../static/img/papers/thumb/rigel.png").default,
      authors:
        "Ran Chen, <u>Di Weng*</u>, Yanwei Huang, Xinhuan Shu, Jiayi Zhou, Guodao Sun, Yingcai Wu",
      title: "Rigel: Transforming Tabular Data by Declarative Mapping",
      venue:
        "IEEE Transactions on Visualization and Computer Graphics, vol. 29, no. 1, pp. 128-138, Jan. 2023",
      doi: "10.1109/TVCG.2022.3209385",
      abstract:
        "We present Rigel, an interactive system for rapid transformation of tabular data. Rigel implements a new declarative mapping approach that formulates the data transformation procedure as direct mappings from data to the row, column, and cell channels of the target table. To construct such mappings, Rigel allows users to directly drag data attributes from input data to these three channels and indirectly drag or type data values in a spreadsheet, and possible mappings that do not contradict these interactions are recommended to achieve efficient and straightforward data transformation. The recommended mappings are generated by enumerating and composing data variables based on the row, column, and cell channels, thereby revealing the possibility of alternative tabular forms and facilitating open-ended exploration in many data transformation scenarios, such as designing tables for presentation. In contrast to existing systems that transform data by composing operations (like transposing and pivoting), Rigel requires less prior knowledge on these operations, and constructing tables from the channels is more efficient and results in less ambiguity than generating operation sequences as done by the traditional by-example approaches. User study results demonstrated that Rigel is significantly less demanding in terms of time and interactions and suits more scenarios compared to the state-of-the-art by-example approach. A gallery of diverse transformation cases is also presented to show the potential of Rigel's expressiveness.",
    },
  ],
  2023: [
    {
      image: require("../../static/img/papers/thumb/geocamera.png").default,
      authors:
        "Wenchao Li, Zhan Wang, Yun Wang, <u>Di Weng</u>, Liwenhan Xie, Siming Chen, Haidong Zhang, Huamin Qu",
      title:
        "GeoCamera: Telling Stories in Geographic Visualizations with Camera Movements",
      venue:
        "Proceedings of the 2023 CHI Conference on Human Factors in Computing Systems (CHI '23)",
      doi: "10.1145/3544548.3581470",
    },
    {
      image: require("../../static/img/papers/thumb/geonetverse.png").default,
      authors:
        "Zikun Deng, Shifu Chen, Xiao Xie, Guodao Sun, Mingliang Xu, <u>Di Weng*</u>, Yingcai Wu*",
      title: "Multilevel Visual Analysis of Aggregate Geo-Networks",
      venue:
        "IEEE Transactions on Visualization and Computer Graphics (Early Access)",
      doi: "10.1109/TVCG.2022.3229953",
    },
    {
      image: require("../../static/img/papers/thumb/ecoalvis.png").default,
      authors:
        "Shuhan Liu, <u>Di Weng*</u>, Yuan Tian, Zikun Deng, Haoran Xu, Xiangyu Zhu, Honglei Yin, Xianyuan Zhan, Yingcai Wu",
      title:
        "ECoalVis: Visual Analysis of Control Strategies in Coal-fired Power Plants",
      venue:
        "IEEE Transactions on Visualization and Computer Graphics, vol. 29, no. 1, pp. 1091-1101, Jan. 2023",
      doi: "10.1109/TVCG.2022.3209430",
    },
    {
      image: require("../../static/img/papers/thumb/rigel.png").default,
      authors:
        "Ran Chen, <u>Di Weng*</u>, Yanwei Huang, Xinhuan Shu, Jiayi Zhou, Guodao Sun, Yingcai Wu",
      title: "Rigel: Transforming Tabular Data by Declarative Mapping",
      venue:
        "IEEE Transactions on Visualization and Computer Graphics, vol. 29, no. 1, pp. 128-138, Jan. 2023",
      doi: "10.1109/TVCG.2022.3209385",
    },
    {
      image: require("../../static/img/papers/thumb/urbansurvey.png").default,
      authors:
        "Zikun Deng, <u>Di Weng*</u>, Shuhan Liu, Yuan Tian, Mingliang Xu, Yingcai Wu*",
      title:
        "A survey of urban visual analytics: Advances and future directions",
      venue: "Computational Visual Media, vol. 9, pp. 3–39, 2023",
      doi: "10.1007/s41095-022-0275-7",
    },
    {
      image: require("../../static/img/papers/thumb/ct3.png").default,
      authors: "Zikun Deng, <u>Di Weng*</u>, Yingcai Wu",
      title:
        "You are experienced: interactive tour planning with crowdsourcing tour data from web",
      venue: "Journal of Visualization, vol. 26, pp. 385–401, 2023",
      doi: "10.1007/s12650-022-00884-1",
    },
  ],
  2022: [
    {
      image: require("../../static/img/papers/thumb/nebula.png").default,
      authors:
        "Ran Chen, Xinhuan Shu, Jiahui Chen, <u>Di Weng</u>, Junxiu Tang, Siwei Fu, Yingcai Wu",
      title: "Nebula: A Coordinating Grammar of Graphics",
      venue:
        "IEEE Transactions on Visualization and Computer Graphics, vol. 28, no. 12, pp. 4127-4140, 2022",
      doi: "10.1109/TVCG.2021.3076222",
    },
    {
      image: require("../../static/img/papers/thumb/viscas.png").default,
      authors:
        "Zikun Deng, <u>Di Weng</u>, Yuxuan Liang, Jie Bao, Yu Zheng, Tobias Schreck, Mingliang Xu, Yingcai Wu",
      title: "Visual Cascade Analytics of Large-Scale Spatiotemporal Data",
      venue:
        "IEEE Transactions on Visualization and Computer Graphics, vol. 28, no. 6, pp. 2486-2499, 2022",
      doi: "10.1109/TVCG.2021.3071387",
    },
    {
      image: require("../../static/img/papers/thumb/ordermonitor.png").default,
      authors:
        "Junxiu Tang, Yuhua Zhou, Tan Tang, <u>Di Weng</u>, Boyang Xie, Lingyun Yu, Huaqiang Zhang, Yingcai Wu",
      title:
        "A Visualization Approach for Monitoring Order Processing in E-Commerce Warehouse",
      venue:
        "IEEE Transactions on Visualization and Computer Graphics, vol. 28, no. 1, pp. 857-867, 2022",
      doi: "10.1109/TVCG.2021.3114878",
    },
    {
      image: require("../../static/img/papers/thumb/compass.png").default,
      authors:
        "Zikun Deng, <u>Di Weng</u>, Xiao Xie, Jie Bao, Yu Zheng, Mingliang Xu, Wei Chen, Yingcai Wu",
      title: "Compass: Towards Better Causal Analysis of Urban Time Series",
      venue:
        "IEEE Transactions on Visualization and Computer Graphics, vol. 28, no. 1, pp. 1051-1061, 2022",
      doi: "10.1109/TVCG.2021.3114875",
    },
  ],
  2021: [
    {
      image: require("../../static/img/papers/thumb/industrial_survey.png")
        .default,
      authors: "Shuhan Liu, <u>Di Weng</u>, Yingcai Wu",
      title: "A Review on Industrial Data Visual Analytics",
      venue:
        "Journal of Integration Technology, vol. 11, no. 6, pp. 3-19, 2021",
      doi: "10.12146/j.issn.2095-3135.20210630003",
    },
    {
      image: require("../../static/img/papers/thumb/corvizor.png").default,
      authors:
        "Yingcai Wu, <u>Di Weng</u>, Zikun Deng, Jie Bao, Mingliang Xu, Zhangye Wang, Yu Zheng, Zhiyu Ding, Wei Chen",
      title:
        "Towards Better Detection and Analysis of Massive Spatiotemporal Co-Occurrence Patterns",
      venue:
        "IEEE Transactions on Intelligent Transportation Systems, vol. 22, no. 6, pp. 3387-3402, 2021",
      doi: "10.1109/TITS.2020.2983226",
    },
    {
      image: require("../../static/img/papers/thumb/bnva.png").default,
      authors:
        "<u>Di Weng</u>, Chengbo Zheng, Zikun Deng, Mingze Ma, Jie Bao, Yu Zheng, Mingliang Xu, Yingcai Wu",
      title: "Towards Better Bus Networks: A Visual Analytics Approach",
      venue:
        "IEEE Transactions on Visualization and Computer Graphics, vol. 27, no. 2, pp. 817-827, 2021",
      doi: "10.1109/TVCG.2020.3030458",
    },
    {
      image: require("../../static/img/papers/thumb/mcrs.png").default,
      authors:
        "<u>Di Weng</u>, Ran Chen, Jianhui Zhang, Jie Bao, Yu Zheng, Yingcai Wu",
      title:
        "Pareto-Optimal Transit Route Planning With Multi-Objective Monte-Carlo Tree Search",
      venue:
        "IEEE Transactions on Intelligent Transportation Systems, vol. 22, no. 2, pp. 1185-1195, 2021",
      doi: "10.1109/TITS.2020.2964012",
    },
  ],
  earlier: [
    {
      image: require("../../static/img/papers/thumb/airvis.png").default,
      authors:
        "Zikun Deng, <u>Di Weng</u>, Jiahui Chen, Ren Liu, Zhibin Wang, Jie Bao, Yu Zheng, Yingcai Wu",
      title: "AirVis: Visual Analytics of Air Pollution Propagation",
      venue:
        "IEEE Transactions on Visualization and Computer Graphics, vol. 26, no. 1, pp. 800-810, 2020",
      doi: "10.1109/TVCG.2019.2934670",
    },
    {
      image: require("../../static/img/papers/thumb/srvis.png").default,
      authors:
        "<u>Di Weng</u>, Ran Chen, Zikun Deng, Feiran Wu, Jingmin Chen, Yingcai Wu",
      title:
        "SRVis: Towards Better Spatial Integration in Ranking Visualization",
      venue:
        "IEEE Transactions on Visualization and Computer Graphics, vol. 25, no. 1, pp. 459-469, 2019",
      doi: "10.1109/TVCG.2018.2865126",
    },
    {
      image: require("../../static/img/papers/thumb/homefinder.png").default,
      authors: "<u>Di Weng</u>, Heming Zhu, Jie Bao, Yu Zheng, Yingcai Wu",
      title:
        "HomeFinder Revisited: Finding Ideal Homes with Reachability-Centric Multi-Criteria Decision Making",
      venue:
        "Proceedings of the 2018 CHI Conference on Human Factors in Computing Systems (CHI '18), Paper 247, 1–12",
      doi: "10.1145/3173574.3173821",
    },
    {
      image: require("../../static/img/papers/thumb/smartadp.png").default,
      authors:
        "Dongyu Liu, <u>Di Weng</u>, Yuhong Li, Jie Bao, Yu Zheng, Huamin Qu, and Yingcai Wu",
      title:
        "SmartAdP: Visual Analytics of Large-scale Taxi Trajectories for Selecting Billboard Locations",
      venue:
        "IEEE Transactions on Visualization and Computer Graphics, vol. 23, no. 1, pp. 1-10, 2017",
      doi: "10.1109/TVCG.2016.2598432",
    },
  ],
};
